POST http://localhost:3000/itens/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzgzOTYyNjAwLCJleHAiOjE3ODQwNDkwMDB9.i8xPVPh3Sk0DKRgO2QcSawLnSYN2aanu-01ncZu4DC4

{
    "nome": "Mamão"
}